### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by alvinwan** [Cal-CS-61A-Staff/ok-redesign#1]
~~ [ ] finish sidebar/pullout ~~

~~add more information to homepage~~
- [x] indication for tooltip (small question mark?)

~~actually finish submission page~~ (just highlight.js magic)
- [x] add logout button

**Comment by Sumukh** [comment]
Tooltip indication: another idea would be dashed underlines. 
The sidebar can have `overflow-y: hidden;`. 
If we are short on time: the homepage can be sparse. It has the most important part (the login button).

**Comment by alvinwan** [comment]
Oh good idea. Sure thing!
