### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok-redesign#3]
![pasted image at 2016_01_07 08_19 pm](https://cloud.githubusercontent.com/assets/882381/12342624/160b9ca0-bae1-11e5-8671-a8461f7f536e.png)

**Comment by alvinwan** [comment]
@Sumukh As nice as this would look, I realized that it would make the mobile design harder (hard to fit everything in the top nav on a small screen). Can I put this off for now?

**Comment by Sumukh** [comment]
Yeah. That's fine.

**Comment by Sumukh** [comment]
Implemented (partially) on the actual ok integration. We can think about how titles can be moved into the navbar later. 

Thanks!

**Comment by Sumukh** [comment]
Side note: `min-height` is [kind of buggy](http://stackoverflow.com/questions/8468066/child-inside-parent-with-min-height-100-not-inheriting-height) so I set `height: 100%` for body/html
